name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]
  workflow_dispatch:

jobs:
  validate:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [18, 20, 21]
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Validate package structure
        run: |
          echo "Validating package.json..."
          node -e "
            const pkg = require('./package.json');
            if (!pkg.bin) throw new Error('No bin entries found');
            if (!pkg.files) throw new Error('No files array found');
            console.log('✅ Package structure is valid');
          "

      - name: Build package
        run: npm run build:package

      - name: Test CLI tools
        run: npm run test:cli

      - name: Test template creation
        run: |
          # Test creating a new project
          mkdir -p test-output
          cd test-output
          node ../bin/create-fe-base.js test-project
          cd test-project
          ls -la
          # Verify key files exist
          test -f package.json || exit 1
          test -f src/App.tsx || exit 1
          test -f vite.config.ts || exit 1
          echo "✅ Template creation test passed"

  lint-template:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: 'template/package-lock.json'

      - name: Install template dependencies
        run: |
          cd template
          npm ci

      - name: Lint template code
        run: |
          cd template
          npm run lint

      - name: Test template
        run: |
          cd template
          npm run test:unit
