name: Publish to DockerHub

on:
  push:
    tags:
      - 'v*'
    branches:
      - main
  workflow_dispatch:

env:
  REGISTRY: docker.io
  IMAGE_NAME: gnimoh001/fe-base-react-template

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    
    permissions:
      contents: read
      packages: write
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=raw,value=latest,enable={{is_default_branch}}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        continue-on-error: true
        id: docker-push
        with:
          context: ./template
          file: ./template/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Check Docker push result
        if: steps.docker-push.outcome == 'failure'
        run: |
          echo "::warning::Docker push failed. This might be due to:"
          echo "::warning::1. DockerHub repository 'gnimoh001/fe-base-react-template' doesn't exist"
          echo "::warning::2. GitHub secrets DOCKER_USERNAME and DOCKER_PASSWORD are not configured"
          echo "::warning::3. Insufficient permissions on the DockerHub repository"
          echo "::warning::Please create the repository on DockerHub and ensure GitHub secrets are set up correctly."

      - name: Update Docker Hub description
        uses: peter-evans/dockerhub-description@v4
        if: steps.docker-push.outcome == 'success'
        continue-on-error: true
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: ${{ env.IMAGE_NAME }}
          short-description: 'fe-base-react-template - Modern React application template with TypeScript, Vite, and Docker support'
          readme-filepath: ./template/README.md
