name: Publish to NPM

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to publish (e.g., v1.0.0)'
        required: true
        default: 'v1.0.0'

jobs:
  publish:
    runs-on: ubuntu-latest
    
    permissions:
      contents: read
      id-token: write
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        run: npm install

      - name: Validate package structure
        run: |
          echo "Validating package.json..."
          node -e "
            const pkg = require('./package.json');
            if (pkg.private) throw new Error('Package is marked as private');
            if (!pkg.bin) throw new Error('No bin entries found');
            if (!pkg.files) throw new Error('No files array found');
            console.log('✅ Package structure is valid');
          "

      - name: Build package
        run: npm run build:package

      - name: Test CLI tools
        run: npm run test:cli

      - name: Publish to NPM
        run: npm publish --provenance --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Create GitHub Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.DEPENDABOT_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: Release ${{ github.ref_name }}
          body: |
            ## Changes
            
            - Updated Fe-Base template package
            - See [CHANGELOG.md](./CHANGELOG.md) for detailed changes
            
            ## Installation
            
            ```bash
            npx @gnimoh001/fe-base my-project
            ```
          draft: false
          prerelease: false
